"""Validation set matrix metadata for Epic 4 Slice 4.13.

This module documents coverage intent across the expanded 24-repository set.
It does not claim pack-precision accuracy; expectations deepen per assessment head.
"""

from __future__ import annotations

from typing import Final

# Active repository_ids in the expanded validation set (exactly these, enabled).
# Order: controlled fixtures, workspace samples, remotes.
ACTIVE_VALIDATION_SET: Final[tuple[str, ...]] = (
    "local-cloud-signals",
    "local-security-hygiene",
    "local-ai-readiness",
    "local-ai-negative",
    "local-architecture-signals",
    "local-complexity-signals",
    "local-dependency-signals",
    "local-terraform-signals",
    "local-serverless-signals",
    "local-compose-managed",
    "local-library-npm",
    "local-cli-python",
    "local-sample-js",
    "local-sample-python",
    "local-sample-php",
    "local-sample-csharp",
    "local-sample-java",
    "local-typescript-app",
    "local-gradle-multimodule",
    "remote-java-spring-petclinic",
    "remote-python-fastapi",
    "remote-typescript-angular",
    "remote-php-bookstack",
    "remote-csharp-eshop",
)

# Matrix rows: repository_id -> coverage dimension flags / labels.
VALIDATION_MATRIX: Final[dict[str, dict[str, str]]] = {
    "local-cloud-signals": {
        "tier": "1",
        "source_type": "local",
        "pinned_source_identity": "engine/validation/fixtures/cloud-signals",
        "language": "shell (minimal)",
        "framework": "n/a",
        "ecosystem": "Docker/Compose",
        "approximate_size": "tiny",
        "expected_runtime": "fast",
        "test_posture": "absent",
        "architecture_coverage": "deployment-oriented",
        "td_coverage": "minimal",
        "dependency_coverage": "container images only",
        "security_coverage": "none intentional",
        "cloud_coverage": "primary (Docker/k8s/GHA)",
        "ai_coverage": "none intentional",
        "modernization_coverage": "cloud readiness",
        "controlled_vs_real_world": "controlled",
        "fast_vs_slow": "fast",
        "license": "CodeStrata-owned",
    },
    "local-security-hygiene": {
        "tier": "1",
        "source_type": "local",
        "pinned_source_identity": "engine/validation/fixtures/security-hygiene",
        "language": "Python",
        "framework": "n/a",
        "ecosystem": "n/a",
        "approximate_size": "tiny",
        "expected_runtime": "fast",
        "test_posture": "absent",
        "architecture_coverage": "minimal",
        "td_coverage": "minimal",
        "dependency_coverage": "none",
        "security_coverage": "primary (fake credentials)",
        "cloud_coverage": "none intentional",
        "ai_coverage": "none intentional",
        "modernization_coverage": "security precision",
        "controlled_vs_real_world": "controlled",
        "fast_vs_slow": "fast",
        "license": "CodeStrata-owned",
    },
    "local-ai-readiness": {
        "tier": "1",
        "source_type": "local",
        "pinned_source_identity": "engine/validation/fixtures/ai-readiness",
        "language": "Python",
        "framework": "OpenAI SDK (declared)",
        "ecosystem": "pip",
        "approximate_size": "tiny",
        "expected_runtime": "fast",
        "test_posture": "absent",
        "architecture_coverage": "minimal",
        "td_coverage": "minimal",
        "dependency_coverage": "pip + openai",
        "security_coverage": "none intentional",
        "cloud_coverage": "none intentional",
        "ai_coverage": "primary (openai + mcp)",
        "modernization_coverage": "modernization chain",
        "controlled_vs_real_world": "controlled",
        "fast_vs_slow": "fast",
        "license": "CodeStrata-owned",
    },
    "local-ai-negative": {
        "tier": "1",
        "source_type": "local",
        "pinned_source_identity": "engine/validation/fixtures/ai-negative",
        "language": "JavaScript (metadata)",
        "framework": "n/a",
        "ecosystem": "npm (name-only dep)",
        "approximate_size": "tiny",
        "expected_runtime": "fast",
        "test_posture": "absent",
        "architecture_coverage": "minimal",
        "td_coverage": "minimal",
        "dependency_coverage": "npm metadata only",
        "security_coverage": "none intentional",
        "cloud_coverage": "none intentional",
        "ai_coverage": "negative control",
        "modernization_coverage": "baseline",
        "controlled_vs_real_world": "controlled",
        "fast_vs_slow": "fast",
        "license": "CodeStrata-owned",
    },
    "local-architecture-signals": {
        "tier": "1",
        "source_type": "local",
        "pinned_source_identity": "engine/validation/fixtures/architecture-signals",
        "language": "Java",
        "framework": "n/a",
        "ecosystem": "n/a",
        "approximate_size": "tiny",
        "expected_runtime": "fast",
        "test_posture": "present (test-only edges)",
        "architecture_coverage": "primary (cycle + layer skip)",
        "td_coverage": "minimal",
        "dependency_coverage": "none",
        "security_coverage": "none intentional",
        "cloud_coverage": "none intentional",
        "ai_coverage": "none intentional",
        "modernization_coverage": "baseline",
        "controlled_vs_real_world": "controlled",
        "fast_vs_slow": "fast",
        "license": "CodeStrata-owned",
    },
    "local-complexity-signals": {
        "tier": "1",
        "source_type": "local",
        "pinned_source_identity": "engine/validation/fixtures/complexity-signals",
        "language": "Python",
        "framework": "n/a",
        "ecosystem": "n/a",
        "approximate_size": "tiny",
        "expected_runtime": "fast",
        "test_posture": "present (excluded from TD)",
        "architecture_coverage": "minimal",
        "td_coverage": "primary (5 TD rules)",
        "dependency_coverage": "none",
        "security_coverage": "none intentional",
        "cloud_coverage": "none intentional",
        "ai_coverage": "none intentional",
        "modernization_coverage": "baseline",
        "controlled_vs_real_world": "controlled",
        "fast_vs_slow": "fast",
        "license": "CodeStrata-owned",
    },
    "local-dependency-signals": {
        "tier": "1",
        "source_type": "local",
        "pinned_source_identity": "engine/validation/fixtures/dependency-signals",
        "language": "Java + Python",
        "framework": "n/a",
        "ecosystem": "Maven + pip",
        "approximate_size": "tiny",
        "expected_runtime": "fast",
        "test_posture": "absent",
        "architecture_coverage": "minimal",
        "td_coverage": "minimal",
        "dependency_coverage": "primary (5 hygiene rules)",
        "security_coverage": "none intentional",
        "cloud_coverage": "none intentional",
        "ai_coverage": "none intentional",
        "modernization_coverage": "baseline",
        "controlled_vs_real_world": "controlled",
        "fast_vs_slow": "fast",
        "license": "CodeStrata-owned",
    },
    "local-terraform-signals": {
        "tier": "1",
        "source_type": "local",
        "pinned_source_identity": "engine/validation/fixtures/terraform-signals",
        "language": "HCL",
        "framework": "Terraform",
        "ecosystem": "Terraform",
        "approximate_size": "tiny",
        "expected_runtime": "fast",
        "test_posture": "absent",
        "architecture_coverage": "minimal",
        "td_coverage": "minimal",
        "dependency_coverage": "none",
        "security_coverage": "none intentional",
        "cloud_coverage": "primary (IaC/AWS stub)",
        "ai_coverage": "none intentional",
        "modernization_coverage": "baseline",
        "controlled_vs_real_world": "controlled",
        "fast_vs_slow": "fast",
        "license": "CodeStrata-owned",
    },
    "local-serverless-signals": {
        "tier": "1",
        "source_type": "local",
        "pinned_source_identity": "engine/validation/fixtures/serverless-signals",
        "language": "Python",
        "framework": "Serverless Framework",
        "ecosystem": "serverless.yml",
        "approximate_size": "tiny",
        "expected_runtime": "fast",
        "test_posture": "absent",
        "architecture_coverage": "minimal",
        "td_coverage": "minimal",
        "dependency_coverage": "none",
        "security_coverage": "none intentional",
        "cloud_coverage": "primary (serverless family)",
        "ai_coverage": "none intentional",
        "modernization_coverage": "baseline",
        "controlled_vs_real_world": "controlled",
        "fast_vs_slow": "fast",
        "license": "CodeStrata-owned",
    },
    "local-compose-managed": {
        "tier": "1",
        "source_type": "local",
        "pinned_source_identity": "engine/validation/fixtures/compose-managed",
        "language": "YAML",
        "framework": "Docker Compose",
        "ecosystem": "Docker/Compose",
        "approximate_size": "tiny",
        "expected_runtime": "fast",
        "test_posture": "absent",
        "architecture_coverage": "minimal",
        "td_coverage": "minimal",
        "dependency_coverage": "container images only",
        "security_coverage": "none intentional",
        "cloud_coverage": "primary (managed services)",
        "ai_coverage": "none intentional",
        "modernization_coverage": "baseline",
        "controlled_vs_real_world": "controlled",
        "fast_vs_slow": "fast",
        "license": "CodeStrata-owned",
    },
    "local-library-npm": {
        "tier": "1",
        "source_type": "local",
        "pinned_source_identity": "engine/validation/fixtures/library-npm",
        "language": "JavaScript",
        "framework": "n/a (library)",
        "ecosystem": "npm",
        "approximate_size": "tiny",
        "expected_runtime": "fast",
        "test_posture": "absent",
        "architecture_coverage": "minimal",
        "td_coverage": "minimal",
        "dependency_coverage": "npm metadata",
        "security_coverage": "none intentional",
        "cloud_coverage": "none intentional",
        "ai_coverage": "none intentional",
        "modernization_coverage": "baseline",
        "controlled_vs_real_world": "controlled",
        "fast_vs_slow": "fast",
        "license": "CodeStrata-owned",
    },
    "local-cli-python": {
        "tier": "1",
        "source_type": "local",
        "pinned_source_identity": "engine/validation/fixtures/cli-python",
        "language": "Python",
        "framework": "argparse CLI",
        "ecosystem": "pip/pyproject",
        "approximate_size": "tiny",
        "expected_runtime": "fast",
        "test_posture": "absent",
        "architecture_coverage": "minimal",
        "td_coverage": "minimal",
        "dependency_coverage": "pyproject only",
        "security_coverage": "none intentional",
        "cloud_coverage": "none intentional",
        "ai_coverage": "none intentional",
        "modernization_coverage": "baseline",
        "controlled_vs_real_world": "controlled",
        "fast_vs_slow": "fast",
        "license": "CodeStrata-owned",
    },
    "local-sample-js": {
        "tier": "2",
        "source_type": "local",
        "pinned_source_identity": "workspace test-fixtures/sample-js-app",
        "language": "JavaScript",
        "framework": "Express",
        "ecosystem": "npm",
        "approximate_size": "small",
        "expected_runtime": "fast",
        "test_posture": "limited/absent",
        "architecture_coverage": "simple",
        "td_coverage": "baseline",
        "dependency_coverage": "npm/package.json",
        "security_coverage": "none intentional",
        "cloud_coverage": "none intentional",
        "ai_coverage": "none intentional",
        "modernization_coverage": "inventory + hygiene",
        "controlled_vs_real_world": "real-world",
        "fast_vs_slow": "fast",
        "license": "CodeStrata-owned",
    },
    "local-sample-python": {
        "tier": "2",
        "source_type": "local",
        "pinned_source_identity": "workspace test-fixtures/sample-python-app",
        "language": "Python",
        "framework": "Flask",
        "ecosystem": "pip/pyproject",
        "approximate_size": "small",
        "expected_runtime": "fast",
        "test_posture": "present (pytest)",
        "architecture_coverage": "service structure",
        "td_coverage": "measurable",
        "dependency_coverage": "pip/pyproject",
        "security_coverage": "none intentional",
        "cloud_coverage": "none intentional",
        "ai_coverage": "none intentional",
        "modernization_coverage": "dep+test+debt",
        "controlled_vs_real_world": "real-world",
        "fast_vs_slow": "fast",
        "license": "CodeStrata-owned",
    },
    "local-sample-php": {
        "tier": "2",
        "source_type": "local",
        "pinned_source_identity": "workspace test-fixtures/sample-php-app",
        "language": "PHP",
        "framework": "Laravel",
        "ecosystem": "Composer",
        "approximate_size": "small",
        "expected_runtime": "fast",
        "test_posture": "present (PHPUnit)",
        "architecture_coverage": "MVC service",
        "td_coverage": "baseline",
        "dependency_coverage": "Composer",
        "security_coverage": "none intentional",
        "cloud_coverage": "none intentional",
        "ai_coverage": "none intentional",
        "modernization_coverage": "inventory",
        "controlled_vs_real_world": "real-world",
        "fast_vs_slow": "fast",
        "license": "CodeStrata-owned",
    },
    "local-sample-csharp": {
        "tier": "2",
        "source_type": "local",
        "pinned_source_identity": "workspace test-fixtures/sample-csharp-app",
        "language": "C#",
        "framework": "ASP.NET",
        "ecosystem": "NuGet",
        "approximate_size": "small",
        "expected_runtime": "fast",
        "test_posture": "present (xUnit)",
        "architecture_coverage": "layered web",
        "td_coverage": "baseline",
        "dependency_coverage": "NuGet",
        "security_coverage": "none intentional",
        "cloud_coverage": "none intentional",
        "ai_coverage": "none intentional",
        "modernization_coverage": "inventory",
        "controlled_vs_real_world": "real-world",
        "fast_vs_slow": "fast",
        "license": "CodeStrata-owned",
    },
    "local-sample-java": {
        "tier": "2",
        "source_type": "local",
        "pinned_source_identity": "workspace test-fixtures/sample-java-app",
        "language": "Java",
        "framework": "Spring Boot",
        "ecosystem": "Maven",
        "approximate_size": "small",
        "expected_runtime": "fast",
        "test_posture": "absent (junit dep only)",
        "architecture_coverage": "minimal single-app",
        "td_coverage": "baseline",
        "dependency_coverage": "Maven",
        "security_coverage": "none intentional",
        "cloud_coverage": "none intentional",
        "ai_coverage": "none intentional",
        "modernization_coverage": "inventory",
        "controlled_vs_real_world": "real-world",
        "fast_vs_slow": "fast",
        "license": "CodeStrata-owned",
    },
    "local-typescript-app": {
        "tier": "2",
        "source_type": "local",
        "pinned_source_identity": "engine/validation/fixtures/typescript-app",
        "language": "TypeScript",
        "framework": "Express",
        "ecosystem": "npm",
        "approximate_size": "small",
        "expected_runtime": "fast",
        "test_posture": "present (Jest)",
        "architecture_coverage": "simple web",
        "td_coverage": "baseline",
        "dependency_coverage": "npm",
        "security_coverage": "none intentional",
        "cloud_coverage": "none intentional",
        "ai_coverage": "none intentional",
        "modernization_coverage": "inventory",
        "controlled_vs_real_world": "controlled",
        "fast_vs_slow": "fast",
        "license": "CodeStrata-owned",
    },
    "local-gradle-multimodule": {
        "tier": "2",
        "source_type": "local",
        "pinned_source_identity": "engine/validation/fixtures/gradle-multimodule",
        "language": "Java",
        "framework": "n/a",
        "ecosystem": "Gradle",
        "approximate_size": "small",
        "expected_runtime": "fast",
        "test_posture": "absent",
        "architecture_coverage": "multi-module",
        "td_coverage": "baseline",
        "dependency_coverage": "Gradle",
        "security_coverage": "none intentional",
        "cloud_coverage": "none intentional",
        "ai_coverage": "none intentional",
        "modernization_coverage": "inventory",
        "controlled_vs_real_world": "controlled",
        "fast_vs_slow": "fast",
        "license": "CodeStrata-owned",
    },
    "remote-java-spring-petclinic": {
        "tier": "3",
        "source_type": "remote",
        "pinned_source_identity": (
            "https://github.com/spring-projects/spring-petclinic.git@"
            "f182358d02e4a68e52bdbabf55ca7800288511e7"
        ),
        "language": "Java",
        "framework": "Spring Boot",
        "ecosystem": "Maven",
        "approximate_size": "medium",
        "expected_runtime": "medium",
        "test_posture": "present",
        "architecture_coverage": "layered multi-package",
        "td_coverage": "measurable complexity",
        "dependency_coverage": "Maven",
        "security_coverage": "uncontrolled third-party",
        "cloud_coverage": "compose/devcontainer",
        "ai_coverage": "none intentional",
        "modernization_coverage": "arch+debt+mod",
        "controlled_vs_real_world": "real-world",
        "fast_vs_slow": "medium",
        "license": "Apache-2.0",
    },
    "remote-python-fastapi": {
        "tier": "3",
        "source_type": "remote",
        "pinned_source_identity": (
            "https://github.com/fastapi/full-stack-fastapi-template.git@"
            "c9e70d65c74f7adda417fc8de0757207ff77514c"
        ),
        "language": "Python",
        "framework": "FastAPI",
        "ecosystem": "pip",
        "approximate_size": "medium",
        "expected_runtime": "medium",
        "test_posture": "present",
        "architecture_coverage": "full-stack service",
        "td_coverage": "measurable",
        "dependency_coverage": "pip/poetry",
        "security_coverage": "uncontrolled",
        "cloud_coverage": "docker-compose",
        "ai_coverage": "none intentional",
        "modernization_coverage": "inventory+debt",
        "controlled_vs_real_world": "real-world",
        "fast_vs_slow": "medium",
        "license": "MIT",
    },
    "remote-typescript-angular": {
        "tier": "3",
        "source_type": "remote",
        "pinned_source_identity": (
            "https://github.com/gothinkster/angular-realworld-example-app.git@"
            "dd99ed2cf39c805d719f943c5d7061a5683d98a8"
        ),
        "language": "TypeScript",
        "framework": "Angular",
        "ecosystem": "npm",
        "approximate_size": "medium",
        "expected_runtime": "medium",
        "test_posture": "present",
        "architecture_coverage": "SPA modules",
        "td_coverage": "measurable",
        "dependency_coverage": "npm",
        "security_coverage": "uncontrolled",
        "cloud_coverage": "none primary",
        "ai_coverage": "none intentional",
        "modernization_coverage": "inventory",
        "controlled_vs_real_world": "real-world",
        "fast_vs_slow": "medium",
        "license": "MIT",
    },
    "remote-php-bookstack": {
        "tier": "3",
        "source_type": "remote",
        "pinned_source_identity": (
            "https://github.com/BookStackApp/BookStack.git@"
            "4e406c41c4c8060a5795e74c66fb96362e54f400"
        ),
        "language": "PHP",
        "framework": "Laravel",
        "ecosystem": "Composer",
        "approximate_size": "large",
        "expected_runtime": "medium",
        "test_posture": "present",
        "architecture_coverage": "layered MVC",
        "td_coverage": "measurable",
        "dependency_coverage": "Composer",
        "security_coverage": "uncontrolled",
        "cloud_coverage": "docker optional",
        "ai_coverage": "none intentional",
        "modernization_coverage": "inventory+debt",
        "controlled_vs_real_world": "real-world",
        "fast_vs_slow": "medium",
        "license": "MIT",
    },
    "remote-csharp-eshop": {
        "tier": "4",
        "source_type": "remote",
        "pinned_source_identity": (
            "https://github.com/dotnet/eShop.git@"
            "9b4f9434f46fdc5c1a6e9e936af2868340cdbc48"
        ),
        "language": "C#",
        "framework": "ASP.NET",
        "ecosystem": "NuGet",
        "approximate_size": "large",
        "expected_runtime": "slow",
        "test_posture": "present",
        "architecture_coverage": "microservices-style",
        "td_coverage": "measurable",
        "dependency_coverage": "NuGet",
        "security_coverage": "uncontrolled",
        "cloud_coverage": "k8s/docker",
        "ai_coverage": "none intentional",
        "modernization_coverage": "synthesis target",
        "controlled_vs_real_world": "real-world",
        "fast_vs_slow": "slow",
        "license": "MIT",
    },
}
