"""Verification contract for clean Community CLI installation (SV.2)."""

from __future__ import annotations

from dataclasses import dataclass, field
from typing import Mapping

CLI_INSTALLATION_VERIFICATION_ID = "cli-installation-verification"
CLI_INSTALLATION_VERIFICATION_VERSION = "1.0.0"
CLI_INSTALLATION_VERIFICATION_URN = (
    f"{CLI_INSTALLATION_VERIFICATION_ID}:{CLI_INSTALLATION_VERIFICATION_VERSION}"
)

# Supported platforms for Community first-time install verification.
# Verification is OS-independent at the Python layer; runners execute on the
# host OS. CI may not exercise every OS — the contract still declares support.
SUPPORTED_OS_FAMILIES: tuple[str, ...] = ("darwin", "linux", "win32")

# Aligns with engine/pyproject.toml requires-python.
MINIMUM_PYTHON = (3, 12)

# First-time Community methods. Editable installs are developer-only and fail
# the clean-install contract when detected.
INSTALLATION_METHODS: tuple[str, ...] = (
    "pip_wheel",
    "pip_sdist",
    "pip_path_non_editable",
)

FORBIDDEN_INSTALL_MARKERS: tuple[str, ...] = (
    "pip install -e",
    "pip install --editable",
    "PYTHONPATH",
)


@dataclass(frozen=True, slots=True)
class ExpectedCommand:
    """Expected CLI invocation and pass criteria."""

    name: str
    argv: tuple[str, ...]
    require_exit_code: int
    stdout_contains: tuple[str, ...] = ()
    stderr_contains: tuple[str, ...] = ()
    notes: str = ""


@dataclass(frozen=True, slots=True)
class InstallationContract:
    """Pass/fail contract for SV.2 clean CLI installation verification."""

    verification_id: str = CLI_INSTALLATION_VERIFICATION_ID
    verification_version: str = CLI_INSTALLATION_VERIFICATION_VERSION
    supported_os_families: tuple[str, ...] = SUPPORTED_OS_FAMILIES
    minimum_python: tuple[int, int] = MINIMUM_PYTHON
    installation_methods: tuple[str, ...] = INSTALLATION_METHODS
    forbidden_markers: tuple[str, ...] = FORBIDDEN_INSTALL_MARKERS
    required_commands: tuple[ExpectedCommand, ...] = field(default_factory=tuple)
    required_config_markers: tuple[str, ...] = (
        "[repository]",
        'path = "."',
        'profile = "community"',
        "[workspace]",
        'directory = ".codestrata/workspace"',
        "[knowledge]",
        "Generated by: codestrata init",
    )
    # init declares workspace/knowledge paths; it does not create those dirs.
    unexpected_after_init: tuple[str, ...] = (
        ".git",
        "node_modules",
        "platform",
        "infrastructure",
    )
    pass_criteria: Mapping[str, str] = field(
        default_factory=lambda: {
            "environment": "Fresh venv; no editable install; no developer PYTHONPATH; "
            "no pre-existing codestrata.toml in the verification workspace.",
            "install": "pip install of wheel, sdist, or non-editable path succeeds.",
            "version": "codestrata --version exits 0 and prints CodeStrata <version>.",
            "help": "codestrata --help exits 0 and lists Primary workflow commands "
            "(there is no `codestrata help` subcommand).",
            "init": "codestrata init creates codestrata.toml with Community markers.",
            "doctor": "After init, codestrata doctor exits 0 with All doctor checks passed.",
            "artifacts": "Only expected config is created; permissions are user-readable; "
            "workspace/knowledge directories are declared but not created by init.",
            "failures": "Documented failure scenarios return non-zero exits with safe messages.",
        }
    )


def default_contract() -> InstallationContract:
    """Return the active SV.2 contract with required happy-path commands."""

    return InstallationContract(
        required_commands=(
            ExpectedCommand(
                name="codestrata_version_flag",
                argv=("--version",),
                require_exit_code=0,
                stdout_contains=("CodeStrata",),
            ),
            ExpectedCommand(
                name="codestrata_help",
                argv=("--help",),
                require_exit_code=0,
                stdout_contains=("Primary workflow", "init", "doctor", "assess"),
                notes="Supported help surface is --help, not a `help` subcommand.",
            ),
            ExpectedCommand(
                name="codestrata_init",
                argv=("init",),
                require_exit_code=0,
                stdout_contains=("Wrote", "Success: Configuration ready."),
            ),
            ExpectedCommand(
                name="codestrata_doctor",
                argv=("doctor",),
                require_exit_code=0,
                stdout_contains=("All doctor checks passed",),
            ),
        )
    )


def python_version_supported(version_info: tuple[int, ...] | None = None) -> bool:
    """Return True when the interpreter meets the contract minimum."""

    import sys

    info = version_info if version_info is not None else sys.version_info[:2]
    major, minor = int(info[0]), int(info[1])
    return (major, minor) >= MINIMUM_PYTHON


def os_family_supported(system: str | None = None) -> bool:
    """Return True when the host OS family is in the supported matrix."""

    import sys

    family = system if system is not None else sys.platform
    # Normalize cygwin/msys to win32-like for documentation; runner uses sys.platform.
    if family.startswith("win"):
        family = "win32"
    return family in SUPPORTED_OS_FAMILIES
