"""Test assessment domain package (Phase 4.6.1)."""

from aimf.domain.testing.assessment.enums import (
    TestAssessmentStatus,
    TestCoverageAreaStatus,
    TestCoverageMaturity,
    TestLimitationCategory,
    TestTraceabilityRelation,
)
from aimf.domain.testing.assessment.identifiers import (
    ARTIFACT_SCHEMA_ID,
    MAX_TRACEABILITY_ENTRIES,
    SCHEMA_NAME,
    SECTION_ID,
    SECTION_SCHEMA_VERSION,
    TESTING_ASSESSMENT_FILENAME,
    build_assessment_id,
    build_configuration_fingerprint,
    build_diagnostic_id,
    build_empty_section_fingerprint,
    build_limitation_id,
    build_trace_edge_id,
)
from aimf.domain.testing.assessment.models import (
    TestAssessmentSection,
    TestConfidenceInventory,
    TestCountBucket,
    TestCoverageArea,
    TestCoverageSummary,
    TestExecutionSummary,
    TestFindingInventory,
    TestLimitation,
    TestRuleInventory,
    TestRuleInventoryEntry,
    TestSeverityInventory,
    TestTraceabilityEdge,
    TestTraceabilityIndex,
)

__all__ = [
    "ARTIFACT_SCHEMA_ID",
    "MAX_TRACEABILITY_ENTRIES",
    "SCHEMA_NAME",
    "SECTION_ID",
    "SECTION_SCHEMA_VERSION",
    "TESTING_ASSESSMENT_FILENAME",
    "TestAssessmentSection",
    "TestAssessmentStatus",
    "TestConfidenceInventory",
    "TestCountBucket",
    "TestCoverageArea",
    "TestCoverageAreaStatus",
    "TestCoverageMaturity",
    "TestCoverageSummary",
    "TestExecutionSummary",
    "TestFindingInventory",
    "TestLimitation",
    "TestLimitationCategory",
    "TestRuleInventory",
    "TestRuleInventoryEntry",
    "TestSeverityInventory",
    "TestTraceabilityEdge",
    "TestTraceabilityIndex",
    "TestTraceabilityRelation",
    "build_assessment_id",
    "build_configuration_fingerprint",
    "build_diagnostic_id",
    "build_empty_section_fingerprint",
    "build_limitation_id",
    "build_trace_edge_id",
]
