"""Deterministic code-cleanup and residency registers for Slice 16.3."""

from __future__ import annotations

from typing import Any

# Each entry: path/symbol, classification, evidence, action, owner, residency,
# dependency_impact, test_impact, compatibility_impact, deletion_status


def cleanup_register() -> list[dict[str, Any]]:
    return [
        {
            "path": "engine/src/codestrata/domain/rules/suppression.py",
            "symbol": "module",
            "classification": "DEAD_REMOVE",
            "evidence": "zero_imports_of_domain.rules.suppression; package __init__ imports applicability",
            "action": "deleted",
            "owner": "engine/domain/rules",
            "residency": "codestrata-engine",
            "dependency_impact": "none",
            "test_impact": "none",
            "compatibility_impact": "none",
            "deletion_status": "deleted",
        },
        {
            "path": "engine/scripts/generate_slice_413.py",
            "symbol": "script",
            "classification": "DEAD_REMOVE",
            "evidence": "one_shot_generator; zero_repo_refs; outputs already under engine/validation/expectations",
            "action": "deleted",
            "owner": "engine/scripts",
            "residency": "codestrata-engine",
            "dependency_impact": "none",
            "test_impact": "none",
            "compatibility_impact": "none",
            "deletion_status": "deleted",
        },
        {
            "path": "vscode-plugin/src/engine/discovery.ts",
            "symbol": "EngineResolution",
            "classification": "DEAD_REMOVE",
            "evidence": "exported_interface_with_zero_references",
            "action": "deleted_symbol",
            "owner": "vscode-plugin",
            "residency": "codestrata-vscode",
            "dependency_impact": "none",
            "test_impact": "none",
            "compatibility_impact": "none",
            "deletion_status": "deleted",
        },
        {
            "path": "vscode-plugin/src/engine/discovery.ts",
            "symbol": "isExecutablePresent",
            "classification": "DEAD_REMOVE",
            "evidence": "exported_function_with_zero_callers",
            "action": "deleted_symbol",
            "owner": "vscode-plugin",
            "residency": "codestrata-vscode",
            "dependency_impact": "none",
            "test_impact": "none",
            "compatibility_impact": "none",
            "deletion_status": "deleted",
        },
        {
            "path": "vscode-plugin/src/engine/discovery.ts",
            "symbol": "pathEntries",
            "classification": "DEAD_REMOVE",
            "evidence": "exported_function_with_zero_callers",
            "action": "deleted_symbol",
            "owner": "vscode-plugin",
            "residency": "codestrata-vscode",
            "dependency_impact": "none",
            "test_impact": "none",
            "compatibility_impact": "none",
            "deletion_status": "deleted",
        },
        {
            "path": "vscode-plugin/src/cliDiscovery/compatibility.ts",
            "symbol": "MIN_DISCOVERY_CLI_VERSION",
            "classification": "ACTIVE_DUPLICATE_REMOVE",
            "evidence": "deprecated_alias; zero_importers; COMPATIBILITY_MINIMUM_CLI is authority",
            "action": "deleted_symbol",
            "owner": "vscode-plugin/cliDiscovery",
            "residency": "codestrata-vscode",
            "dependency_impact": "none",
            "test_impact": "none",
            "compatibility_impact": "alias_removed_authority_retained",
            "deletion_status": "deleted",
        },
        {
            "path": "platform/src/codestrata_platform/community_cloud_api/extension_events/catalog.py",
            "symbol": "comment_cursor_plugin",
            "classification": "LEGACY_REMOVE",
            "evidence": "comment_referenced_absent_cursor_plugin; product_dir_absent",
            "action": "comment_updated",
            "owner": "platform/community_cloud_api",
            "residency": "codestrata-platform",
            "dependency_impact": "none",
            "test_impact": "none",
            "compatibility_impact": "none",
            "deletion_status": "updated",
        },
        {
            "path": "vscode-plugin/src/engine/discovery.ts",
            "symbol": "listEngineCandidates",
            "classification": "OWNER_REVIEW_REQUIRED",
            "evidence": "deprecated_but_still_called_by_onboarding_firstRun",
            "action": "retain",
            "owner": "vscode-plugin",
            "residency": "codestrata-vscode",
            "dependency_impact": "none",
            "test_impact": "tests_still_cover",
            "compatibility_impact": "compatibility_bridge",
            "deletion_status": "retained",
        },
        {
            "path": "scripts/export-public-repos.py",
            "symbol": "community_exporter_impl",
            "classification": "OWNER_REVIEW_REQUIRED",
            "evidence": "authoritative_community_export_impl_loaded_by_router_adapter",
            "action": "retain",
            "owner": "scripts/export",
            "residency": "codestrata-platform",
            "dependency_impact": "none",
            "test_impact": "release_verification",
            "compatibility_impact": "export_authority",
            "deletion_status": "retained",
        },
        {
            "path": "scripts/export_infrastructure_repository.py",
            "symbol": "compat_wrapper",
            "classification": "COMPATIBILITY_RETAIN",
            "evidence": "intentional_slice_12_8_wrapper_to_router; verification_asserts_presence",
            "action": "retain",
            "owner": "scripts/export",
            "residency": "codestrata-platform",
            "dependency_impact": "none",
            "test_impact": "export_verification",
            "compatibility_impact": "compat_cli",
            "deletion_status": "retained",
        },
        {
            "path": "engine/src/codestrata/infrastructure/knowledge_store/sqlite/migrations.py",
            "symbol": "aimf_version_rename",
            "classification": "COMPATIBILITY_RETAIN",
            "evidence": "required_sqlite_column_rename_for_old_dbs; not_active_product_identity",
            "action": "retain",
            "owner": "engine/knowledge_store",
            "residency": "codestrata-engine",
            "dependency_impact": "none",
            "test_impact": "schema_tests",
            "compatibility_impact": "db_migration",
            "deletion_status": "retained",
        },
        {
            "path": "cursor-plugin/",
            "symbol": "product_tree",
            "classification": "ACTIVE_KEEP",
            "evidence": "directory_absent; absence_is_correct_posture",
            "action": "verify_absent",
            "owner": "community",
            "residency": "n/a",
            "dependency_impact": "none",
            "test_impact": "cursor_removal_verifiers",
            "compatibility_impact": "none",
            "deletion_status": "already_absent",
        },
        {
            "path": "scripts/run_e2e_validation_assess.py",
            "symbol": "script",
            "classification": "OWNER_REVIEW_REQUIRED",
            "evidence": "zero_external_refs; maintainer_tooling_pair_with_preserve_validation_artifacts",
            "action": "retain",
            "owner": "scripts",
            "residency": "codestrata-platform",
            "dependency_impact": "none",
            "test_impact": "unknown",
            "compatibility_impact": "none",
            "deletion_status": "retained",
        },
        {
            "path": "platform/demo/",
            "symbol": "package",
            "classification": "ACTIVE_KEEP",
            "evidence": "oss_demonstration_surface_with_verification_consumers",
            "action": "retain",
            "owner": "platform/demo",
            "residency": "codestrata-platform",
            "dependency_impact": "none",
            "test_impact": "platform_verification",
            "compatibility_impact": "none",
            "deletion_status": "retained",
        },
        {
            "path": "engine/src/codestrata/ai/provider_adapters/*/legacy_bridge.py",
            "symbol": "legacy_bridge",
            "classification": "COMPATIBILITY_RETAIN",
            "evidence": "actively_used_by_provider_migration_verification_and_runtime_folding",
            "action": "retain",
            "owner": "engine/ai",
            "residency": "codestrata-engine",
            "dependency_impact": "none",
            "test_impact": "engine/verification/ai_provider_*",
            "compatibility_impact": "provider_compat",
            "deletion_status": "retained",
        },
        {
            "path": "*.sqlite / reports/verification/**",
            "symbol": "generated_storage",
            "classification": "DEFER_TO_STORAGE_CLEANUP",
            "evidence": "slice_16_6_owns_generated_artifact_cleanup",
            "action": "defer",
            "owner": "ops",
            "residency": "generated",
            "dependency_impact": "none",
            "test_impact": "none",
            "compatibility_impact": "none",
            "deletion_status": "deferred",
        },
        {
            "path": "package dependencies",
            "symbol": "deps",
            "classification": "DEFER_TO_DEPENDENCY_CLEANUP",
            "evidence": "slice_16_5_owns_dependency_cleanup",
            "action": "defer",
            "owner": "ops",
            "residency": "n/a",
            "dependency_impact": "candidates_recorded",
            "test_impact": "none",
            "compatibility_impact": "none",
            "deletion_status": "deferred",
        },
        {
            "path": "platform commercial prototype packages",
            "symbol": "intelligence_reporting_etc",
            "classification": "OWNER_REVIEW_REQUIRED",
            "evidence": "not_community_v0_2_0_required_but_not_proven_obsolete",
            "action": "retain",
            "owner": "platform",
            "residency": "codestrata-platform",
            "dependency_impact": "none",
            "test_impact": "platform_tests",
            "compatibility_impact": "none",
            "deletion_status": "retained",
        },
        {
            "path": "major package relocations",
            "symbol": "residency",
            "classification": "DEFER_TO_REPOSITORY_SPLIT",
            "evidence": "slice_16_7_owns_repository_boundary_residency_cleanup",
            "action": "defer",
            "owner": "architecture",
            "residency": "pending",
            "dependency_impact": "none",
            "test_impact": "none",
            "compatibility_impact": "none",
            "deletion_status": "deferred",
        },
    ]


def residency_register() -> list[dict[str, Any]]:
    return [
        {
            "package": "engine/",
            "current_repository": "codestrata-platform monorepo",
            "current_path": "engine/",
            "owner": "Community Engine",
            "expected_future_repository": "codestrata-engine",
            "status": "ACTIVE_KEEP",
        },
        {
            "package": "platform/community_cloud_api",
            "current_repository": "codestrata-platform monorepo",
            "current_path": "platform/src/codestrata_platform/community_cloud_api/",
            "owner": "Platform Community Cloud",
            "expected_future_repository": "codestrata-platform",
            "status": "ACTIVE_KEEP",
        },
        {
            "package": "platform/intelligence_reporting",
            "current_repository": "codestrata-platform monorepo",
            "current_path": "platform/src/codestrata_platform/intelligence_reporting/",
            "owner": "Platform commercial EI",
            "expected_future_repository": "codestrata-platform",
            "status": "OWNER_REVIEW_REQUIRED",
        },
        {
            "package": "platform/rag",
            "current_repository": "codestrata-platform monorepo",
            "current_path": "platform/src/codestrata_platform/rag/",
            "owner": "Platform RAG",
            "expected_future_repository": "codestrata-platform",
            "status": "OWNER_REVIEW_REQUIRED",
        },
        {
            "package": "platform/knowledge_graph",
            "current_repository": "codestrata-platform monorepo",
            "current_path": "platform/src/codestrata_platform/",
            "owner": "Platform KG",
            "expected_future_repository": "codestrata-platform",
            "status": "OWNER_REVIEW_REQUIRED",
        },
        {
            "package": "vscode-plugin/",
            "current_repository": "codestrata-platform monorepo",
            "current_path": "vscode-plugin/",
            "owner": "Community VS Code",
            "expected_future_repository": "codestrata-vscode",
            "status": "ACTIVE_KEEP",
        },
        {
            "package": "insights/",
            "current_repository": "codestrata-platform monorepo",
            "current_path": "insights/",
            "owner": "Community Insights SPA",
            "expected_future_repository": "codestrata-insights",
            "status": "ACTIVE_KEEP",
        },
        {
            "package": "infrastructure/",
            "current_repository": "codestrata-platform monorepo",
            "current_path": "infrastructure/",
            "owner": "Infrastructure",
            "expected_future_repository": "codestrata-infrastructure",
            "status": "DEFER_TO_REPOSITORY_SPLIT",
        },
        {
            "package": "docs/",
            "current_repository": "codestrata-platform monorepo",
            "current_path": "docs/",
            "owner": "Community Docs",
            "expected_future_repository": "codestrata-docs",
            "status": "ACTIVE_KEEP",
        },
        {
            "package": "scripts/repository_export_router",
            "current_repository": "codestrata-platform monorepo",
            "current_path": "scripts/repository_export_router/",
            "owner": "Export authority",
            "expected_future_repository": "codestrata-platform",
            "status": "ACTIVE_KEEP",
        },
        {
            "package": "design-system/",
            "current_repository": "codestrata-platform monorepo",
            "current_path": "design-system/",
            "owner": "Design System",
            "expected_future_repository": "codestrata-platform (shared)",
            "status": "ACTIVE_KEEP",
        },
    ]


def dependency_candidates() -> list[str]:
    return [
        "Record-only for Slice 16.5: no dependency removals in 16.3",
        "After dead-code removal, re-scan engine[dev]/mcp] and vscode-plugin package.json unused deps",
        "Platform optional extras (pgvector/mcp) remain OWNER_REVIEW for commercial packages",
    ]


def classification_counts(register: list[dict[str, Any]]) -> dict[str, int]:
    counts: dict[str, int] = {}
    for row in register:
        cls = row["classification"]
        counts[cls] = counts.get(cls, 0) + 1
    return dict(sorted(counts.items()))
