"""Verification contract for ``codestrata init`` (SV.3)."""

from __future__ import annotations

from dataclasses import dataclass, field

CLI_INITIALIZATION_VERIFICATION_ID = "cli-initialization-verification"
CLI_INITIALIZATION_VERIFICATION_VERSION = "1.0.0"
CLI_INITIALIZATION_VERIFICATION_URN = (
    f"{CLI_INITIALIZATION_VERIFICATION_ID}:{CLI_INITIALIZATION_VERIFICATION_VERSION}"
)

# Scenario IDs exercised by the runner.
SCENARIO_IDS: tuple[str, ...] = (
    "A_minimal_supported_repository",
    "B_empty_repository",
    "C_existing_valid_configuration",
    "D_malformed_existing_configuration",
    "E_unwritable_repository",
    "F_nested_working_directory",
    "G_path_containing_spaces",
    "H_non_interactive_environment",
    "I_unsupported_repository_shape",
    "J_existing_unrelated_files",
    "K_determinism_pair",
)

REQUIRED_CONFIG_MARKERS: tuple[str, ...] = (
    "# Generated by: codestrata init",
    "[repository]",
    'path = "."',
    'profile = "community"',
    "[workspace]",
    'directory = ".codestrata/workspace"',
    "[knowledge]",
    "enabled = false",
    "[static_analysis]",
    "[ai]",
    'provider = "bedrock"',
)

FORBIDDEN_CONFIG_MARKERS: tuple[str, ...] = (
    "AKIA",
    "aws_secret",
    "api_key",
    "password",
    "BEGIN PRIVATE KEY",
    "cscc_v1_",
)

# Generated by successful init (required).
REQUIRED_ARTIFACTS: tuple[str, ...] = ("codestrata.toml",)

# Must not appear after init-only (forbidden).
FORBIDDEN_ARTIFACTS: tuple[str, ...] = (
    "report.json",
    "findings.json",
    "reports/report.json",
    "platform",
    "infrastructure",
    ".env",
    "credentials.json",
)

# Optional / not created by init (declared in config only).
OPTIONAL_DECLARED_DIRS: tuple[str, ...] = (
    ".codestrata/workspace",
    ".codestrata/knowledge",
)


@dataclass(frozen=True, slots=True)
class InitializationContract:
    """Pass/fail contract for SV.3 initialization verification."""

    verification_id: str = CLI_INITIALIZATION_VERIFICATION_ID
    verification_version: str = CLI_INITIALIZATION_VERIFICATION_VERSION
    scenario_ids: tuple[str, ...] = SCENARIO_IDS
    required_config_markers: tuple[str, ...] = REQUIRED_CONFIG_MARKERS
    forbidden_config_markers: tuple[str, ...] = FORBIDDEN_CONFIG_MARKERS
    required_artifacts: tuple[str, ...] = REQUIRED_ARTIFACTS
    forbidden_artifacts: tuple[str, ...] = FORBIDDEN_ARTIFACTS
    optional_declared_dirs: tuple[str, ...] = OPTIONAL_DECLARED_DIRS
    # Current product: no git/repo-root discovery; config is written relative to cwd/--config.
    discovers_repository_root: bool = False
    # Current product: no interactive prompts on init.
    interactive: bool = False
    # Current product: init does not enable knowledge/telemetry pipelines.
    telemetry_enabled_by_default: bool = False
    # AI provider key may be present; assess still requires explicit --with-ai.
    ai_silently_enabled: bool = False
    network_required: bool = False
    help_command: tuple[str, ...] = ("--help",)
    init_flags: tuple[str, ...] = ("--config", "-c", "--force")
    notes: tuple[str, ...] = (
        "Init scaffolds codestrata.toml only; it does not create workspace/knowledge directories.",
        "Existing configuration (valid or malformed) is refused without --force.",
        "Nested cwd writes config into that cwd — no upward root discovery.",
        "Supported help surface is codestrata --help (no help subcommand).",
    )


def default_contract() -> InitializationContract:
    return InitializationContract()
