"""Schema identity for Repository Knowledge Layer artifacts."""

from __future__ import annotations

KNOWLEDGE_DOCUMENT_SCHEMA_NAME = "knowledge-document"
KNOWLEDGE_DOCUMENT_SCHEMA_VERSION = "1.0.0"

KNOWLEDGE_CHUNK_SCHEMA_NAME = "knowledge-chunk"
KNOWLEDGE_CHUNK_SCHEMA_VERSION = "1.0.0"

VECTOR_RECORD_SCHEMA_NAME = "vector-record"
VECTOR_RECORD_SCHEMA_VERSION = "1.0.0"

KNOWLEDGE_CORPUS_SCHEMA_NAME = "knowledge-corpus"
KNOWLEDGE_CORPUS_SCHEMA_VERSION = "1.0.0"

KNOWLEDGE_PROJECTION_SCHEMA_NAME = "knowledge-projection"
KNOWLEDGE_PROJECTION_SCHEMA_VERSION = "1.0.0"

DETERMINISTIC_CHUNKER_SCHEMA_NAME = "deterministic-chunker"
DETERMINISTIC_CHUNKER_SCHEMA_VERSION = "1.0.0"

EMBEDDING_RESULT_SCHEMA_NAME = "embedding-result"
EMBEDDING_RESULT_SCHEMA_VERSION = "1.0.0"

KNOWLEDGE_INDEX_MANIFEST_SCHEMA_NAME = "knowledge-index-manifest"
KNOWLEDGE_INDEX_MANIFEST_SCHEMA_VERSION = "1.0.0"

KNOWLEDGE_INDEX_RESULT_SCHEMA_NAME = "knowledge-index-result"
KNOWLEDGE_INDEX_RESULT_SCHEMA_VERSION = "1.0.0"

REPOSITORY_RETRIEVAL_REQUEST_SCHEMA_NAME = "repository-retrieval-request"
REPOSITORY_RETRIEVAL_REQUEST_SCHEMA_VERSION = "1.0.0"

REPOSITORY_RETRIEVAL_RESULT_SCHEMA_NAME = "repository-retrieval-result"
REPOSITORY_RETRIEVAL_RESULT_SCHEMA_VERSION = "1.0.0"

RETRIEVAL_HIT_SCHEMA_NAME = "retrieval-hit"
RETRIEVAL_HIT_SCHEMA_VERSION = "1.0.0"

RETRIEVAL_CONTEXT_SCHEMA_NAME = "retrieval-context"
RETRIEVAL_CONTEXT_SCHEMA_VERSION = "1.0.0"

GROUNDED_ANSWER_REQUEST_SCHEMA_NAME = "grounded-answer-request"
GROUNDED_ANSWER_REQUEST_SCHEMA_VERSION = "1.0.0"

GROUNDED_ANSWER_RESULT_SCHEMA_NAME = "grounded-answer-result"
GROUNDED_ANSWER_RESULT_SCHEMA_VERSION = "1.0.0"

GROUNDED_ANSWER_SCHEMA_NAME = "grounded-answer"
GROUNDED_ANSWER_SCHEMA_VERSION = "1.0.0"

ANSWER_STATEMENT_SCHEMA_NAME = "answer-statement"
ANSWER_STATEMENT_SCHEMA_VERSION = "1.0.0"

ANSWER_CITATION_SCHEMA_NAME = "answer-citation"
ANSWER_CITATION_SCHEMA_VERSION = "1.0.0"

MCP_TOOL_REQUEST_SCHEMA_NAME = "mcp-tool-request"
MCP_TOOL_REQUEST_SCHEMA_VERSION = "1.0.0"

MCP_TOOL_RESPONSE_SCHEMA_NAME = "mcp-tool-response"
MCP_TOOL_RESPONSE_SCHEMA_VERSION = "1.0.0"

MCP_HEALTH_RESPONSE_SCHEMA_NAME = "mcp-health-response"
MCP_HEALTH_RESPONSE_SCHEMA_VERSION = "1.0.0"

MCP_SERVER_MANIFEST_SCHEMA_NAME = "mcp-server-manifest"
MCP_SERVER_MANIFEST_SCHEMA_VERSION = "1.0.0"
