import type { MetricResult } from "../metrics/metricResult";

const WINDOW = {
  start_date_utc: "2026-07-10",
  end_date_utc: "2026-08-08",
  horizon: "bounded_period",
} as const;

/** Clearly synthetic MetricResults for component tests — not live data. */
export const SYNTHETIC_MOCK_RESULTS: MetricResult[] = [
  {
    metric_id: "total_anonymous_installations",
    status: "ok",
    window: { ...WINDOW, horizon: "retention_window" },
    value: 0,
    groups: [],
    completeness: "complete",
    denominator: null,
    share: null,
    limitations: ["production_ingestion_still_unwired", "no_live_dashboard_data_claim"],
  },
  {
    metric_id: "daily_active_installations",
    status: "ok",
    window: { ...WINDOW, horizon: "daily" },
    value: 0,
    groups: [],
    completeness: "complete",
    denominator: null,
    share: null,
    limitations: ["no_live_dashboard_data_claim"],
  },
  {
    metric_id: "monthly_active_installations",
    status: "ok",
    window: { ...WINDOW, horizon: "rolling_30_day" },
    value: null,
    groups: [],
    completeness: "unavailable",
    denominator: null,
    share: null,
    limitations: ["source_unavailable"],
  },
  {
    metric_id: "cli_version_adoption",
    status: "ok",
    window: WINDOW,
    value: 8,
    groups: [
      {
        dimension: "client_version",
        key: "0.2.0",
        count: 5,
        share: 0.625,
        suppressed: false,
      },
      {
        dimension: "client_version",
        key: "other_suppressed",
        count: 3,
        share: 0.375,
        suppressed: true,
      },
    ],
    completeness: "partial",
    denominator: 8,
    share: null,
    limitations: ["suppressed_small_groups", "no_live_dashboard_data_claim"],
  },
  {
    metric_id: "language_ecosystem_distribution",
    status: "ok",
    window: WINDOW,
    value: 10,
    groups: [
      {
        dimension: "primary_language",
        key: "typescript",
        count: 6,
        share: 0.6,
        suppressed: false,
      },
      {
        dimension: "primary_language",
        key: "python",
        count: 4,
        share: 0.4,
        suppressed: false,
      },
      {
        dimension: "package_ecosystem",
        key: "npm",
        count: 6,
        share: 0.6,
        suppressed: false,
      },
      {
        dimension: "package_ecosystem",
        key: "other_suppressed",
        count: 4,
        share: 0.4,
        suppressed: true,
      },
    ],
    completeness: "complete",
    denominator: 10,
    share: null,
    limitations: ["suppressed_small_groups"],
  },
  {
    metric_id: "ai_model_adoption",
    status: "ok",
    window: WINDOW,
    value: 7,
    groups: [
      {
        dimension: "model_family",
        key: "claude",
        count: 4,
        share: 0.571,
        suppressed: false,
      },
      {
        dimension: "model_family",
        key: "gpt",
        count: 3,
        share: 0.429,
        suppressed: false,
      },
    ],
    completeness: "complete",
    denominator: 7,
    share: null,
    limitations: [],
  },
  {
    metric_id: "release_adoption",
    status: "ok",
    window: WINDOW,
    value: 9,
    groups: [
      {
        dimension: "cli_client_version",
        key: "0.2.0",
        count: 5,
        share: 0.556,
        suppressed: false,
      },
      {
        dimension: "vscode_client_version",
        key: "0.2.0",
        count: 4,
        share: 0.444,
        suppressed: false,
      },
    ],
    completeness: "complete",
    denominator: 9,
    share: null,
    limitations: [],
  },
  {
    metric_id: "validation_dataset_growth",
    status: "ok",
    window: { ...WINDOW, horizon: "external" },
    value: 42,
    groups: [],
    completeness: "complete",
    denominator: null,
    share: null,
    limitations: ["validation_growth_snapshots_unavailable"],
  },
];
