"""Static branding assets for CodeStrata HTML reports."""

from __future__ import annotations

from functools import lru_cache
from importlib.resources import files

BRAND_NAME = "CodeStrata"
BRAND_REPORT_NAME = "Engineering Assessment"
BRAND_REPORT_TITLE = f"{BRAND_NAME} {BRAND_REPORT_NAME}"
BRAND_FOOTER_LINE = "Generated by CodeStrata Community Edition"
BRAND_VERSION = "0.1.0"

BRAND_MARK_ASSET = "codestrata-mark-mono.svg"


@lru_cache(maxsize=1)
def brand_mark_svg() -> str:
    """Return the packaged monochrome brand mark for inline embedding.

    The mark inherits its ink from the surrounding surface, so the same asset
    renders correctly in screen and print report contexts.
    """

    markup = files("codestrata.reporting.assets").joinpath(BRAND_MARK_ASSET).read_text("utf-8")
    return markup.strip()
