"""Static branding assets for CodeStrata HTML reports."""

from __future__ import annotations

import base64
from functools import lru_cache
from importlib.resources import files

BRAND_NAME = "CodeStrata"
BRAND_REPORT_NAME = "Engineering Assessment"
BRAND_REPORT_TITLE = f"{BRAND_NAME} {BRAND_REPORT_NAME}"
BRAND_FOOTER_LINE = "Generated by CodeStrata Community Edition"
BRAND_VERSION = "0.1.0"

BRAND_MARK_ASSET = "codestrata-mark-mono.svg"
BRAND_FAVICON_ASSET = "favicon-32.png"
# Bound embedded favicon payload so reports stay lightweight/standalone.
_MAX_FAVICON_BYTES = 4096


@lru_cache(maxsize=1)
def brand_mark_svg() -> str:
    """Return the packaged monochrome brand mark for inline embedding.

    The mark inherits its ink from the surrounding surface, so the same asset
    renders correctly in screen and print report contexts.
    """

    markup = files("codestrata.reporting.assets").joinpath(BRAND_MARK_ASSET).read_text("utf-8")
    return markup.strip()


@lru_cache(maxsize=1)
def brand_favicon_data_uri() -> str:
    """Return a data-URI favicon for standalone/offline HTML reports.

    Uses the packaged CodeStrata 32×32 PNG (same brand kit as public surfaces).
    Embedded so local and published reports do not depend on external URLs.
    """

    raw = files("codestrata.reporting.assets").joinpath(BRAND_FAVICON_ASSET).read_bytes()
    if len(raw) > _MAX_FAVICON_BYTES:
        raise RuntimeError(
            f"Packaged favicon {BRAND_FAVICON_ASSET} exceeds {_MAX_FAVICON_BYTES} bytes"
        )
    encoded = base64.standard_b64encode(raw).decode("ascii")
    return f"data:image/png;base64,{encoded}"


def brand_favicon_link_tag() -> str:
    """Return the HTML ``<link rel="icon">`` tag for report ``<head>``."""

    href = brand_favicon_data_uri()
    return f'<link rel="icon" type="image/png" href="{href}">'
