"""Community Cloud API request validation foundation (Slice 7.3)."""

from __future__ import annotations

from codestrata_platform.community_cloud_api.constants import (
    COMMUNITY_REQUEST_VALIDATION_POLICY_VERSION,
    MAX_VALIDATION_ERROR_DETAILS,
)
from codestrata_platform.community_cloud_api.validation.errors import (
    FIELD_INVALID,
    FIELD_INVALID_ENUM,
    FIELD_INVALID_FORMAT,
    FIELD_INVALID_TYPE,
    FIELD_MISSING,
    FIELD_TOO_LARGE,
    FIELD_TOO_LONG,
    FIELD_TOO_SHORT,
    FIELD_TOO_SMALL,
    FIELD_UNKNOWN,
    FIELD_UNSAFE_VALUE,
    build_validation_error_response,
    field_error,
)
from codestrata_platform.community_cloud_api.validation.models import (
    NO_BODY_SCHEMA,
    BodyPolicy,
    CommunityApiRequestModel,
    RequestSchemaDescriptor,
    RequestValidationResult,
    SafeValidationDiagnostic,
    UnknownFieldPolicy,
    ValidationFieldError,
)
from codestrata_platform.community_cloud_api.validation.schema import (
    DEFAULT_MAX_DICT_ITEMS,
    DEFAULT_MAX_LIST_ITEMS,
    ApiClientName,
    ApiClientVersion,
    ApiEventId,
    ApiEventName,
    ApiIdentifier,
    ApiInstallationId,
    ApiPlatformName,
    ApiRepositoryLanguage,
    ApiRepositoryRelativePath,
    ApiSafeLabel,
    ApiSafeMetadataKey,
    ApiSafeMetadataValue,
    ApiSchemaVersion,
    ApiStrictBool,
    ApiStrictInt,
    ApiTimestampString,
)
from codestrata_platform.community_cloud_api.validation.validator import (
    build_safe_diagnostic,
    validate_request_body,
)

__all__ = [
    "COMMUNITY_REQUEST_VALIDATION_POLICY_VERSION",
    "DEFAULT_MAX_DICT_ITEMS",
    "DEFAULT_MAX_LIST_ITEMS",
    "FIELD_INVALID",
    "FIELD_INVALID_ENUM",
    "FIELD_INVALID_FORMAT",
    "FIELD_INVALID_TYPE",
    "FIELD_MISSING",
    "FIELD_TOO_LARGE",
    "FIELD_TOO_LONG",
    "FIELD_TOO_SHORT",
    "FIELD_TOO_SMALL",
    "FIELD_UNKNOWN",
    "FIELD_UNSAFE_VALUE",
    "MAX_VALIDATION_ERROR_DETAILS",
    "NO_BODY_SCHEMA",
    "ApiClientName",
    "ApiClientVersion",
    "ApiEventId",
    "ApiEventName",
    "ApiIdentifier",
    "ApiInstallationId",
    "ApiPlatformName",
    "ApiRepositoryLanguage",
    "ApiRepositoryRelativePath",
    "ApiSafeLabel",
    "ApiSafeMetadataKey",
    "ApiSafeMetadataValue",
    "ApiSchemaVersion",
    "ApiStrictBool",
    "ApiStrictInt",
    "ApiTimestampString",
    "BodyPolicy",
    "CommunityApiRequestModel",
    "RequestSchemaDescriptor",
    "RequestValidationResult",
    "SafeValidationDiagnostic",
    "UnknownFieldPolicy",
    "ValidationFieldError",
    "build_safe_diagnostic",
    "build_validation_error_response",
    "field_error",
    "validate_request_body",
]
