"""Scaffold a minimal Community Edition codestrata.toml."""

from __future__ import annotations

from pathlib import Path
from typing import Annotated

import typer

MINIMAL_CODESTRATA_TOML = """\
# CodeStrata Community Edition — minimal configuration
# Generated by: codestrata init
#
# Quick start:
#   codestrata doctor
#   codestrata assess --repo . --output reports --no-ai

[repository]
# Local path (default: current directory). Or use a GitHub URL:
#   url = "https://github.com/ORG/REPO"
#   branch = "main"
path = "."

profile = "community"

[workspace]
directory = ".codestrata/workspace"
clean_before_clone = true

[knowledge]
directory = ".codestrata/knowledge"
enabled = false

[static_analysis]
enabled = false

[ai]
provider = "bedrock"
"""


def write_minimal_config(path: Path, *, force: bool = False) -> Path:
    """Write a minimal codestrata.toml. Raises FileExistsError unless force."""

    target = path.expanduser()
    if target.exists() and not force:
        raise FileExistsError(
            f"Configuration already exists: {target}\n\n"
            "Fix: omit --force to keep it, or pass --force to overwrite."
        )
    target.parent.mkdir(parents=True, exist_ok=True)
    target.write_text(MINIMAL_CODESTRATA_TOML, encoding="utf-8")
    return target


def register_init_command(app: typer.Typer) -> None:
    """Register ``codestrata init``."""

    @app.command("init")
    def init_command(
        config: Annotated[
            Path,
            typer.Option(
                "--config",
                "-c",
                help="Path for the codestrata.toml to create.",
            ),
        ] = Path("codestrata.toml"),
        force: Annotated[
            bool,
            typer.Option(
                "--force",
                help="Overwrite an existing configuration file.",
            ),
        ] = False,
    ) -> None:
        """Scaffold a minimal codestrata.toml for Community Edition.

        After init:

            codestrata doctor
            codestrata assess --repo . --output reports --no-ai
        """

        try:
            written = write_minimal_config(config, force=force)
        except FileExistsError as error:
            typer.secho(str(error), fg=typer.colors.RED, err=True)
            raise typer.Exit(code=1) from error
        except OSError as error:
            typer.secho(
                f"Failed to write configuration: {error}",
                fg=typer.colors.RED,
                err=True,
            )
            raise typer.Exit(code=1) from error

        typer.echo(f"Wrote {written}")
        typer.echo("Next:")
        typer.echo("  codestrata doctor")
        typer.echo("  codestrata assess --repo . --output reports --no-ai")


__all__ = [
    "MINIMAL_CODESTRATA_TOML",
    "register_init_command",
    "write_minimal_config",
]
