"""Completion scenario matrix (A–Z)."""

from __future__ import annotations

COMPLETION_SCENARIOS: tuple[tuple[str, str], ...] = (
    ("A", "clean_activation"),
    ("B", "cli_unavailable"),
    ("C", "cli_incompatible"),
    ("D", "clean_initialization"),
    ("E", "already_initialized"),
    ("F", "standard_assessment"),
    ("G", "ai_assessment_safe_mock"),
    ("H", "assessment_failure"),
    ("I", "cancellation"),
    ("J", "report_missing"),
    ("K", "report_open_failure"),
    ("L", "recovery_retry_action"),
    ("M", "telemetry_allow"),
    ("N", "telemetry_deny"),
    ("O", "non_interactive"),
    ("P", "sequential_consent_decisions"),
    ("Q", "source_local_standard_assessment"),
    ("R", "ai_engine_provider_boundary"),
    ("S", "package_inventory"),
    ("T", "clean_install"),
    ("U", "update"),
    ("V", "cursor_absence"),
    ("W", "marketplace_claims"),
    ("X", "schema_version_consistency"),
    ("Y", "epic14_absent"),
    ("Z", "no_commit_tag_publish_deploy"),
)

NEGATIVE_COMPLETION_CHECKS: tuple[tuple[str, str], ...] = (
    ("A", "cursor_active_package"),
    ("B", "extension_version_drift"),
    ("C", "assessment_schema_drift"),
    ("D", "cli_0_1_x_accepted"),
    ("E", "cli_1_x_accepted"),
    ("F", "automatic_cli_installation"),
    ("G", "init_writes_config_from_extension"),
    ("H", "assessment_invoked_twice"),
    ("I", "ai_silent_fallback"),
    ("J", "fake_progress_percentage"),
    ("K", "unsafe_report_path_accepted"),
    ("L", "recovery_auto_executes"),
    ("M", "telemetry_consent_persists"),
    ("N", "machineId_read"),
    ("O", "installation_identity_created"),
    ("P", "telemetry_http_activated"),
    ("Q", "source_upload_path"),
    ("R", "direct_ai_sdk_in_extension"),
    ("S", "community_cloud_client"),
    ("T", "data_lake_client"),
    ("U", "marketplace_claims_production_telemetry"),
    ("V", "marketplace_claims_cursor"),
    ("W", "package_contains_tests_verification_reports"),
    ("X", "stale_epic13_incomplete_docs"),
    ("Y", "epic14_implementation_starts"),
    ("Z", "completion_report_leaks"),
)
