/** Slice 13.12 Marketplace branding public exports. */

export {
  MARKETPLACE_BRANDING_POLICY_ID,
  MARKETPLACE_BRANDING_POLICY_VERSION,
  MARKETPLACE_PRODUCT_NAME,
  MARKETPLACE_DISPLAY_NAME,
  MARKETPLACE_PUBLISHER_NAME,
  MARKETPLACE_EXTENSION_VERSION,
  MARKETPLACE_TAGLINE,
  MARKETPLACE_GALLERY_BANNER_COLOR,
  MARKETPLACE_GALLERY_BANNER_THEME,
  MARKETPLACE_GALLERY_ORDER,
  MARKETPLACE_REQUIRED_ASSETS,
  MARKETPLACE_APPROVED_ASSET_TYPES,
  DEFAULT_MARKETPLACE_BRANDING_LIMITATIONS,
  createMarketplaceBrandingPolicy,
  marketplaceBrandingPolicyToStableDict,
  type MarketplaceBrandingPolicy,
} from "./policy";

export {
  FORBIDDEN_MARKETPLACE_CLAIM_PATTERNS,
  marketplaceTextContainsForbiddenClaim,
} from "./claims";
