"""SV.7 contract constants."""

from __future__ import annotations

from codestrata_platform.community_cloud_api.constants import (
    COMMUNITY_AUTHENTICATION_POLICY_VERSION,
    COMMUNITY_CLIENT_CREDENTIAL_FORMAT_VERSION,
    COMMUNITY_CLOUD_API_SCHEMA_VERSION,
    COMMUNITY_EVENT_IDENTITY_POLICY_VERSION,
    COMMUNITY_LOGGING_POLICY_VERSION,
    COMMUNITY_PAYLOAD_LIMIT_POLICY_VERSION,
    COMMUNITY_RATE_LIMIT_POLICY_VERSION,
    COMMUNITY_REQUEST_VALIDATION_POLICY_VERSION,
    COMMUNITY_TELEMETRY_SCHEMA_VERSION,
)

from verification.community_cloud_api.contract import (
    COMMUNITY_CLOUD_API_VERIFICATION_ID,
    COMMUNITY_CLOUD_API_VERIFICATION_VERSION,
    EXPECTED_ROUTE_IDENTITIES,
)


def test_contract_constants() -> None:
    assert COMMUNITY_CLOUD_API_VERIFICATION_ID == "community-cloud-api-verification"
    assert COMMUNITY_CLOUD_API_VERIFICATION_VERSION == "1.0.0"
    assert len(EXPECTED_ROUTE_IDENTITIES) == 6
    assert EXPECTED_ROUTE_IDENTITIES[0] == "health.get"


def test_policy_versions_unchanged() -> None:
    assert COMMUNITY_CLOUD_API_SCHEMA_VERSION == "1.0"
    assert COMMUNITY_AUTHENTICATION_POLICY_VERSION == "1.0"
    assert COMMUNITY_CLIENT_CREDENTIAL_FORMAT_VERSION == "1"
    assert COMMUNITY_RATE_LIMIT_POLICY_VERSION == "1.1"
    assert COMMUNITY_REQUEST_VALIDATION_POLICY_VERSION == "1.0"
    assert COMMUNITY_PAYLOAD_LIMIT_POLICY_VERSION == "1.0"
    assert COMMUNITY_LOGGING_POLICY_VERSION == "1.0"
    assert COMMUNITY_EVENT_IDENTITY_POLICY_VERSION == "1.0"
    assert COMMUNITY_TELEMETRY_SCHEMA_VERSION == "1.0"
