/**
 * Persist assessment context for Cursor conversational workflows.
 * Writes a Cursor project rule from public artifacts only (no source parsing).
 */

import * as fs from "node:fs";
import * as os from "node:os";
import * as path from "node:path";
import { createHash } from "node:crypto";

import type { ConversationContext } from "./context";

export const CURSOR_RULE_RELATIVE_PATH = path.join(
  ".cursor",
  "rules",
  "codestrata-engineering.mdc"
);

export const GENERATED_FILE_MARKER = "codestrata-generated-cursor-rule:v1";

export function cursorRuleAbsolutePath(workspaceFolder: string): string {
  return path.join(workspaceFolder, CURSOR_RULE_RELATIVE_PATH);
}

export function isCodestrataManagedRule(contents: string): boolean {
  return contents.includes(GENERATED_FILE_MARKER);
}

export function renderCursorRule(context: ConversationContext): string {
  const fingerprint = createHash("sha256")
    .update(context.contentFingerprint)
    .digest("hex")
    .slice(0, 16);

  const frontmatter = [
    "---",
    "description: CodeStrata Engineering Assessment context (auto-generated)",
    "alwaysApply: true",
    "---",
    "",
  ].join("\n");

  const header = [
    `<!-- ${GENERATED_FILE_MARKER} -->`,
    `<!-- fingerprint: ${fingerprint} -->`,
    `<!-- generated-at: ${context.generatedAt} -->`,
    context.schemaVersion
      ? `<!-- report-schema: ${context.schemaVersion} -->`
      : "<!-- report-schema: unspecified -->",
    context.engineVersion
      ? `<!-- engine-version: ${context.engineVersion} -->`
      : "<!-- engine-version: unknown -->",
    context.repositoryLabel
      ? `<!-- repository: ${context.repositoryLabel} -->`
      : "<!-- repository: unknown -->",
    "",
    "This file is generated by the **CodeStrata Cursor Extension** from **CodeStrata Engine**",
    "public assessment artifacts. It is not an independent analysis of the repository.",
    "Do not invent findings. Refresh or clear via CodeStrata commands only.",
    "",
  ].join("\n");

  return frontmatter + header + context.markdown;
}

export function writeCursorConversationRule(
  workspaceFolder: string,
  context: ConversationContext
): { path: string; wrote: boolean } {
  const target = cursorRuleAbsolutePath(workspaceFolder);
  const next = renderCursorRule(context);
  if (fs.existsSync(target)) {
    const previous = fs.readFileSync(target, "utf8");
    if (!isCodestrataManagedRule(previous) && previous.trim().length > 0) {
      throw new Error(
        `Refusing to overwrite non-CodeStrata Cursor rule at ${CURSOR_RULE_RELATIVE_PATH}`
      );
    }
    // Skip rewrite when fingerprint unchanged (ignore generated-at drift).
    const prevFp = previous.match(/<!-- fingerprint: ([a-f0-9]+) -->/)?.[1];
    const nextFp = next.match(/<!-- fingerprint: ([a-f0-9]+) -->/)?.[1];
    if (prevFp && nextFp && prevFp === nextFp) {
      return { path: target, wrote: false };
    }
  }

  fs.mkdirSync(path.dirname(target), { recursive: true });
  const temp = path.join(
    path.dirname(target),
    `.codestrata-engineering.${process.pid}.${Date.now()}.tmp`
  );
  try {
    fs.writeFileSync(temp, next, "utf8");
    fs.renameSync(temp, target);
  } catch (error) {
    try {
      if (fs.existsSync(temp)) {
        fs.unlinkSync(temp);
      }
    } catch {
      // ignore cleanup
    }
    throw error;
  }
  return { path: target, wrote: true };
}

export function clearCursorConversationRule(workspaceFolder: string): {
  removed: boolean;
  skippedForeign?: boolean;
} {
  const target = cursorRuleAbsolutePath(workspaceFolder);
  if (!fs.existsSync(target)) {
    return { removed: false };
  }
  const contents = fs.readFileSync(target, "utf8");
  if (!isCodestrataManagedRule(contents)) {
    return { removed: false, skippedForeign: true };
  }
  fs.unlinkSync(target);
  return { removed: true };
}

/** Best-effort: never delete sibling user rules under .cursor/rules. */
export function listSiblingCursorRules(workspaceFolder: string): string[] {
  const dir = path.join(workspaceFolder, ".cursor", "rules");
  if (!fs.existsSync(dir)) {
    return [];
  }
  return fs
    .readdirSync(dir)
    .filter((name) => name !== "codestrata-engineering.mdc")
    .map((name) => path.join(dir, name));
}

export function redactAbsoluteHomePaths(text: string): string {
  const home = os.homedir();
  if (!home) {
    return text;
  }
  return text.split(home).join("~");
}
